default_install_hook_types:
  - pre-commit
  - commit-msg

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: local
    hooks:
      # Install rustfmt via `rustup component add rustfmt` (https://github.com/rust-lang/rustfmt)
      - id: rustfmt
        entry: cargo fmt --all --check
        name: rustfmt
        language: system
        pass_filenames: false
      - id: cargo-build
        entry: cargo build
        name: cargo build
        language: system
        pass_filenames: false
      - id: cargo-test
        entry: cargo test
        name: cargo test
        language: system
        pass_filenames: false
